### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by willyue** [MOLPay/molpay-mobile-xdk-ios#1]
![simulator screen shot 10 may 2016 6 40 25 pm](https://cloud.githubusercontent.com/assets/2383740/15143916/b8af9516-16de-11e6-9294-0b83c82c3c64.png)

After dismissed the view and present it again, there will be gap between the content and navigation bar.

**Comment by clewlb** [comment]
@willyue, please instantiate a new instant for the next payment. It is MOLPay's mobile payment nature that one instant process only one payment. Also, it is recommended to use two decimal point in all amount values. Thanks.
