### ISSUE TITLE
Error copying matching creds

### ISSUE THREAD

**Issue by precious171** [MOLPay/molpay-mobile-xdk-ios#4]
i get this error when using the api

CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "MOLPay API Client";
    srvr = "www.onlinepayment.com.my";
    sync = syna;
}

followed by
Optional([AnyHashable("Error"): Communication Error, please check internet connection, username, or password])

**Comment by clewlb** [comment]
@precious171, thanks for reaching out, you will need a valid merchant credentials to perform a real payment, please email to support@molpay.com to request for one if you haven't got one yet, if you already an existing MOLPay merchant, please email to mobile@molpay.com with your merchant information, so we can assist you further from there. However, if you just want to try out this sdk without wanting to reach out for a valid merchant account, you can set the parameter "mp_sandbox_mode" to true for an offline payment simulation.
