### ISSUE TITLE
Payment page problem- Keep showing Finalizing payment status

### ISSUE THREAD

**Issue by ZackTvZ** [MOLPay/molpay-mobile-xdk-ios#6]
[Screen Recording 2019-02-21 at 10.22.19 AM.zip](https://github.com/MOLPay/molpay-mobile-xdk-ios/files/2887373/Screen.Recording.2019-02-21.at.10.22.19.AM.zip)

**Comment by ZackTvZ** [comment]
FYI I am using express mode

**Comment by clewlb** [comment]
@ZackTvZ Please check the XDK return data from the callback and dismiss the view controller accordingly.
